# Install required software
- hosts: kube-master:kube-node
  become: yes
  tasks:
   - name: Get Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   # Note: currently the latest repository is still xenial not bionic
   - name: Add Kubernetes APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'
      
   # Install packages
   - name: Install required software
     apt: 
       name: "{{ packages }}"
       update_cache: true
       state: present
     register: kubernetes_installed
     vars:
       packages:
       - docker.io
       - kubelet
       - kubeadm

   # Docker service is disabled by default
   - name: enable Docker service
     systemd:
       name: docker
       enabled: yes

# Disable Swap
# https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
   - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
     shell: |
      swapoff -a
     when: kubernetes_installed.changed

   - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
     replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
     when: kubernetes_installed.changed

